'use client';
import { useMemo, useState } from 'react';
import { Search, Plus, X } from 'lucide-react';
import { members as seedMembers, reservations as seedReservations, Member, Reservation } from '@/lib/demo-data';
export function MembersManager(){const [items,setItems]=useState<Member[]>(seedMembers);const [q,setQ]=useState('');const [open,setOpen]=useState(false);const filtered=useMemo(()=>items.filter(x=>(x.name+x.phone+x.interest).includes(q)),[items,q]);
 const add=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setItems([{id:Date.now(),name:String(f.get('name')),phone:String(f.get('phone')),birthday:String(f.get('birthday')),visits:0,interest:String(f.get('interest')),memo:String(f.get('memo'))},...items]);setOpen(false)};
 return <><div className="toolbar"><div className="search"><Search size={18}/><input placeholder="이름, 전화번호, 관심 분야 검색" value={q} onChange={e=>setQ(e.target.value)}/></div><button className="btn btn-primary" onClick={()=>setOpen(true)}><Plus size={17}/>회원 등록</button></div><div className="card table-wrap"><table className="table"><thead><tr><th>회원명</th><th>연락처</th><th>생년월일</th><th>방문</th><th>관심 분야</th><th>메모</th><th></th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><b>{x.name}</b></td><td>{x.phone}</td><td>{x.birthday}</td><td>{x.visits}회</td><td><span className="badge">{x.interest}</span></td><td>{x.memo}</td><td><button className="btn btn-danger" onClick={()=>setItems(items.filter(i=>i.id!==x.id))}>삭제</button></td></tr>)}</tbody></table></div>{open&&<Modal title="신규 회원 등록" close={()=>setOpen(false)}><form onSubmit={add} className="form"><input className="field" name="name" placeholder="이름" required/><input className="field" name="phone" placeholder="연락처" required/><input className="field" name="birthday" type="date" required/><input className="field" name="interest" placeholder="관심 분야"/><textarea className="field" name="memo" placeholder="메모"/><button className="btn btn-primary">등록하기</button></form></Modal>}<CommonStyle/></>}
export function ReservationsManager(){const [items,setItems]=useState<Reservation[]>(seedReservations);const [open,setOpen]=useState(false);const add=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setItems([{id:Date.now(),date:String(f.get('date')),time:String(f.get('time')),name:String(f.get('name')),phone:String(f.get('phone')),status:'대기',memo:String(f.get('memo'))},...items]);setOpen(false)};return <><div className="toolbar"><div><span className="badge">오늘 예약 {items.filter(x=>x.date==='2026-07-23').length}건</span></div><button className="btn btn-primary" onClick={()=>setOpen(true)}><Plus size={17}/>예약 등록</button></div><div className="card table-wrap"><table className="table"><thead><tr><th>날짜</th><th>시간</th><th>이름</th><th>연락처</th><th>상태</th><th>내용</th><th>상태 변경</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.date}</td><td><b>{x.time}</b></td><td>{x.name}</td><td>{x.phone}</td><td><span className="badge">{x.status}</span></td><td>{x.memo}</td><td><select className="field" value={x.status} onChange={e=>setItems(items.map(i=>i.id===x.id?{...i,status:e.target.value as Reservation['status']}:i))}>{['대기','확정','완료','취소'].map(s=><option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table></div>{open&&<Modal title="예약 등록" close={()=>setOpen(false)}><form onSubmit={add} className="form"><input className="field" name="date" type="date" required/><input className="field" name="time" type="time" required/><input className="field" name="name" placeholder="이름" required/><input className="field" name="phone" placeholder="연락처" required/><textarea className="field" name="memo" placeholder="상담 내용"/><button className="btn btn-primary">예약 등록</button></form></Modal>}<CommonStyle/></>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="overlay"><div className="card modal"><header><h2>{title}</h2><button onClick={close}><X/></button></header>{children}</div></div>}
function CommonStyle(){return <style jsx global>{`.toolbar{display:flex;justify-content:space-between;gap:12px;margin:18px 0}.toolbar .btn{display:flex;align-items:center;gap:7px}.search{min-width:330px;background:#fff;border:1px solid var(--line);border-radius:12px;padding:0 12px;display:flex;align-items:center;gap:8px}.search input{border:0;outline:0;padding:12px;width:100%}.overlay{position:fixed;inset:0;background:rgba(10,30,22,.45);z-index:50;display:grid;place-items:center;padding:18px}.modal{width:min(520px,100%);padding:24px}.modal header{display:flex;justify-content:space-between;align-items:center}.modal header button{background:none;border:0;cursor:pointer}.form{display:grid;gap:12px}.form textarea{min-height:100px;resize:vertical}@media(max-width:600px){.toolbar{align-items:stretch}.search{min-width:0;flex:1}.toolbar .btn{font-size:0}.toolbar .btn svg{margin:0}}`}</style>}
